services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: devpulse
      POSTGRES_USER: devpulse
      POSTGRES_PASSWORD: devpulse
    ports:
      - "5432:5432"
    volumes:
      - devpulse-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  devpulse-postgres-data:
